spring.application.name=bankapp
# MySQL Database configuration
spring.datasource.url=jdbc:mysql://bankappdb.ckzwyao0w2by.us-east-1.rds.amazonaws.com/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Spring Boot Actuator & Prometheus Observability
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=always
